export const Users = [
    {
        name: "Daniel Huang",
        role: "Founder",
        description: "Accenture Hacker by day, but developer, product manager, sales guy by night.",
        linkedin: "https://www.linkedin.com/company/wix-com/",
        picture_src: "",
    },
    {
        name: "Calvin Fronda",
        role: "Front-End Engineer",
        description: "Favorite part of the day: Waking up to my homemade cold brew to start the morning.",
        linkedin: "https://www.linkedin.com/in/calvinfronda/",
        picture_src: "",
    },
    {
        name: "Ryan Gedwill",
        role: "Front-End Engineer",
        description: "Favorite life hack: Put cream in before the coffee so it doesn't need to be stirred",
        linkedin: "https://www.linkedin.com/in/ryan-gedwill-a87960107/",
        picture_src: "",
    },
    {
        name: "Greg Glinoga",
        role: "Front-End Engineer",
        description: "Professional background includes data visualization and business intelligence.",
        linkedin: "https://www.linkedin.com/in/greg-glinoga-a7442243/",
        picture_src: "",
    },
    {
        name: "Wilson Lam",
        role: "Front-End Engineer",
        description: "Gamer, Coder, Foodie. Commodity I wish I had more of: Time.",
        linkedin: "https://www.linkedin.com/in/wilson-lam87/",
        picture_src: "",
    },
    {
        name: "Katie Ho",
        role: "Product Designer",
        description: "In my free time, I love traveling and discovering new coffee spots.",
        linkedin: "https://www.linkedin.com/in/katiebelleho/",
        picture_src: "",
    },
    {
        name: "Matthew Li",
        role: "Backend Engineer",
        description: "CS at UC Santa Barbara. Passionate rower from the shores of Lake Cachuma.",
        linkedin: "https://www.linkedin.com/in/matthew-li-mli/",
        picture_src: "",
    },
    {
        name: "Novia Elvina",
        role: "Product Designer",
        description: "I love exploring new places and learn new things!",
        linkedin: "https://www.linkedin.com/in/novia-elvina-700a2473/",
        picture_src: "",
    },
    {
        name: "Gaby Chan",
        role: "Lead Product Designer",
        description: "Master’s student in the UW MHCI+D program and an avid street and concert photographer",
        linkedin: "https://www.linkedin.com/in/gaby-chan/",
        picture_src: "",
    },
    {
        name: "Jerry Li",
        role: "Lead Backend Engineer",
        description: "Software Engineer at Robinhood When not transforming food into code or getting lost in data, I like to play badminton, solve puzzles, and play board games!",
        linkedin: "https://www.linkedin.com/in/jerrylinew/",
        picture_src: "",
    },
    {
        name: "Neil Allavarpu",
        role: "Front-End Engineer",
        description: "Junior at Amador Valley High School. Loves to code and relax.",
        linkedin: "",
        picture_src: "",
    },
    {
        name: "Jeffrey Su",
        role: "Front-End Engineer",
        description: "Frontend Engineer Senior at AVHS. Loves to play video games and card games.",
        linkedin: "https://www.linkedin.com/in/jeffrey-su-09b0831a1/",
        picture_src: "",
    },
]